In [12]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [13]:
heart_data = pd.read_csv("heart.csv")

In [14]:
# Check for nulls in all columns
heart_data.isnull().sum()
# We can see that there are no nulls in the dataset
# So from this data we are looking to apply data pre-processing
features = heart_data.drop('target', axis = 1)
target = heart_data['target']


In [15]:
# Split into train, test split
X_train, y_train, X_test, y_test = train_test_split(features, target, test_size = 0.2)

In [16]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, X_test)

SVC(kernel='linear')

In [17]:
y_pred = svclassifier.predict(y_train)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

[[22  9]
 [ 4 26]]
              precision    recall  f1-score   support

           0       0.85      0.71      0.77        31
           1       0.74      0.87      0.80        30

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.80      0.79      0.79        61



In [19]:
# Now lets try the same idea with a Gaussian Kernel
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, X_test)

SVC()

In [20]:
y_pred = svclassifier.predict(y_train)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[16 15]
 [ 5 25]]
              precision    recall  f1-score   support

           0       0.76      0.52      0.62        31
           1       0.62      0.83      0.71        30

    accuracy                           0.67        61
   macro avg       0.69      0.67      0.66        61
weighted avg       0.69      0.67      0.66        61



In [21]:
svclassifier = SVC(kernel = 'sigmoid')
svclassifier.fit(X_train, X_test)

SVC(kernel='sigmoid')

In [22]:
# Prediction and Evaluation
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[16 15]
 [ 5 25]]
              precision    recall  f1-score   support

           0       0.76      0.52      0.62        31
           1       0.62      0.83      0.71        30

    accuracy                           0.67        61
   macro avg       0.69      0.67      0.66        61
weighted avg       0.69      0.67      0.66        61

